### ISSUE TITLE
VTL expression without $ around any variable

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Eno#1061] opened 2024-07-04 15:03 UTC
Given a VTL expression (on a sequence, question label...) , the value is not well generated in lunatic.json if no variable has a $.
Then the expression is not interpreted

Example:

_NB: I added line breaks in VTL expressions for readability_

- bad case:

```
if (nvl(PRENOMREFB,"")="" or PRENOM=PRENOMREF) 
then "Prénoms des habitants du logement (en commençant par le vôtre)" 
else ""
```

after generation =>

```json
"label": {
            "type": "VTL|MD",
            "value": "\"if (nvl(PRENOMREFB,\"\")=\"\" or PRENOM=PRENOMREF) then \"Prénoms des habitants du logement (en commençant par le vôtre)\" else \"\""
          }
```

- good case: 

```
if (nvl(PRENOMREFB,"")="" or $PRENOM$=PRENOMREF) 
then "Prénoms des habitants du logement (en commençant par le vôtre)" 
else ""
```

after generation =>

```json
"label": {
            "type": "VTL|MD",
            "value": "if (nvl(PRENOMREFB,\"\")=\"\" or PRENOM=PRENOMREF) then \"Prénoms des habitants du logement (en commençant par le vôtre)\" else \"\" "
          }
```

Nb : it would work if i put `$` around any of the variables, here i did around `$PRENOM$` but i could put it around `$PRENOMREF$` instead. The difference is only if there is absolutely no `$`

**Comment by nsenave** [comment] 2024-08-05 15:47
Here actually both cases are bad.

The result you have is due to two reasons:

### Reason 1: the `$` around variables thing

The current way VTL expressions are inputted in Pogues is by adding `$` around variable names.

The reason is that Eno will identify the variables in the Pogues -> DDI transformation, and use this to generate the `"bindingDependencies"` in the DDI -> Lunatic transformation.

This $ thing is not ideal and is a frequent source of user errors, but we can't do much better for now. I've been thinking of a Pogues-Back-Office control that would detect variable names without the $ signs around them, to show a warning to the user, but I didn't take the time to implement such a control yet.

### Reason 2: static labels

The second part of this is due to a combination of:

- the absence of distinction between static and dynamic labels in Pogues UI (I think there is an issue about it in Pogues),
- and a dirty trick in Eno to compensate that.

If a user inputs a label somewhere in Pogues without any variable (i.e. without any variable between `$` signs), they are free to do it without `"` quotes.

The problem is: for any label, Lunatic expects to find a valid VTL expression.

So, Eno has a "dirty trick": if a label has no variables, it adds quotes `"` around the label if necessary to make it a valid VTL string expression.

---

This is why the "good case" is actually bad: the `PRENOMREF` has not been stated as a variable by the user, which is not consistent with the Pogues UI convention.

Actually, indeed, knowing which variables are used in a dynamic label is not required for the Lunatic generation, since there is no binding dependencies for labels. However, it would not be advisable to let the user input variables without `$` at some places, since it is absolutely required for calculated variables (we'd better be consistent about this). So I think things should stay as they are for now.

If that makes sense you can close the issue.

**Closed** 2024-09-23 14:23 UTC
Labels: wontfix
